alpha: 0.1
batch_size: 32
cbuffer_size: 128
ccond_sample: false
hidden_features: 32
img_shape: !!python/tuple
- 1
- 56
- 56
lmbd: 0.1
lr: 0.0001
lr_gamma: 0.97
lr_stepsize: 2
m_in: 0
m_out: -10
num_classes: 42
num_epochs: 20
step_size_decay: 1.0
steps: 60
